name: CI Laravel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer, phpstan, php-cs-fixer

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run linting
      run: composer lint

    - name: Run linting fix (optional)
      run: composer lint:fix

    - name: Run static analysis
      run: composer analyse

    - name: Generate Swagger documentation
      run: composer swagger:generate

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run tests
      run: composer test

    - name: Build application
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Upload Laravel build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: application-build
        path: |
          bootstrap/cache
          storage/framework
