name: CI/CD Laravel

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  
  build:
    environment: testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer, phpstan, php-cs-fixer

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Generate Laravel application key
      run: php artisan key:generate --env=testing

    - name: Run linting
      run: composer lint

    - name: Run linting fix (optional)
      run: composer lint:fix

    - name: Run static analysis
      run: composer analyse

    - name: Generate Swagger documentation
      run: composer swagger:generate

    - name: Run database migrations
      run: php artisan migrate --env=testing --force

    - name: Run tests
      run: php artisan test --env=testing

    - name: Build application
      run: |
        php artisan config:cache --env=testing
        php artisan route:cache --env=testing
        php artisan view:cache --env=testing

    - name: Upload Laravel build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application-build
        path: |
          bootstrap/cache
          storage/framework
          storage/logs
          public

  deploy:
    runs-on: ubuntu-latest
    needs: build  
    environment: production

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: application-build

    - name: Setup SSH for deployment
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy application to server
      run: |
        rsync -avz --delete ./ user@your-server.com:/path/to/your/laravel/app
        ssh user@your-server.com "cd /path/to/your/laravel/app && composer install --no-dev --prefer-dist && php artisan migrate --force --env=production && php artisan config:cache --env=production && php artisan route:cache --env=production && php artisan view:cache --env=production"
