name: CI Laravel

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        tools: composer, phpstan, php-cs-fixer

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run linting
      run: vendor/bin/php-cs-fixer fix --dry-run --diff

    - name: Run static analysis
      run: vendor/bin/phpstan analyse --memory-limit=256M

    - name: Run database migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test

    - name: Build application
      run: |
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Upload Laravel build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: application-build
        path: |
          bootstrap/cache
          storage/framework

